# Generated by Django 4.1.5 on 2023-01-14 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1250, unique=True)),
                ('calory_per_hr', models.IntegerField(default=0, null=True)),
                ('approve_by_admin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1250, unique=True)),
                ('calory', models.IntegerField(default=0, null=True)),
                ('carbs', models.IntegerField(default=0, null=True)),
                ('fat', models.IntegerField(default=0, null=True)),
                ('protein', models.IntegerField(default=0, null=True)),
                ('approve_by_admin', models.IntegerField(default=0)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='food/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('timespend', models.IntegerField(null=True)),
                ('calory_burnout', models.IntegerField(default=0, null=True)),
                ('asses_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.activity')),
                ('foodname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.foods')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
